### PR TITLE
Strip Newline Characters from End of Secret Files

### PR DESCRIPTION
**Pull request by chriscannon**
One of the repeated mistakes we have made when using the `k8s-secrets-from-s3` script is that there *should not* be a newline character at the end of the secrets file uploaded to S3. Since most text editors do this by default (and in my opinion rightfully so) newline characters would get inserted into our secrets and our apps would fail because the value for the environment variable incorrectly contained a newline character at the end. To work around this and maintain backwards compatibility I added a new flag to the `k8s-secrets-from-s3` command to strip all newline characters from the end of a secrets file.

### CODE REVIEW

**Comment by philipcristiano** [comment]
Thanks @chriscannon for the PR! 

This option was discussed (a little) in an internal Slack channel. I'm inclined to avoid mutating the values from S3. I would lean more to helper for putting the file into S3 in a format that works well for reading as an environment variable. Stripping the file of newlines gets messy when using volumes for secrets as POSIX files require terminating newlines. This change would necessitate 2 sets of secrets if the usage model were mixed.

Any thoughts @reactiveops/technical-team-members ?

The general case of this was discussed in kubernetes/kubernetes#23404.

**Comment by chriscannon** [comment]
@philipcristiano Just out of curiosity, what is the use case for using a volume as a secret?

**Comment by philipcristiano** [comment]
@chriscannon sorry, that could have been explained better. The case of mounting secrets as a volume instead of using environment variables. It can avoid verbose deployments as more secrets are added as it does not require configuration for each variable in the deployment file.

**Comment by chriscannon** [comment]
Ah I see, ok thanks for the explanation. I agree that a script for creating secrets could also work and be very helpful at the same time. It definitely gets tedious creating a file locally, making sure the newline is gone, and then uploading to S3. I'll make another PR with this suggestion.

**Comment by philipcristiano** [comment]
Thanks @chriscannon. I haven't explored the idea much to have an idea of what the command would look like. It would be nice to keep it similar to other commands (reading a config file/defaulting to one) to allow for easy setting of vars. 

Other than `-f` I believe we default to envvars over CLI args.

**Comment by ejether** [comment]
Closing this stale PR

**Pull request closed without merging**
