### PR TITLE
readme: Recommend install from NPMjs instead of GH

### PR DESCRIPTION
**Pull request by philipcristiano**
This will install the `rok8s-scripts` package from NPMjs. The previous
version would be installed from Github ( org/project notation for NPM).

The packaged version is now automatically released when following the
release process.

### CODE REVIEW

**Comment by philipcristiano** [comment]
@reactiveops/technical-team-members Hey, the packaged version is now automatically released when tags are pushed. Anyone have concerns before recommending the packaged version?

**Comment by jmound** [comment]
Nothing comes to mind. Perhaps we should update the `package.json`s in the examples dir as well?

**Comment by philipcristiano** [comment]
At the moment they do use the packaged version as they just list the name and `*` version.

**Comment by jmound** [comment]
My mistake. I was looking at [package.json#L7](https://github.com/reactiveops/rok8s-scripts/blob/master/examples/production-ready/package.json#L7) and not the dependencies on line 12.

**Comment by philipcristiano** [comment]
Merging as there are no more comments to address.

**Pull request merged**
