### PR TITLE
Add deployment rollback option

### PR DESCRIPTION
**Pull request by bjaworski3**

### CODE REVIEW

**Comment by bjaworski3** [comment]
This actually won't work if you deploy multiple at once, not all will get rolled back. Let me look into it more

**Comment by bjaworski3** [comment]
Ready for review @coreypobrien

**Comment by bjaworski3** [comment]
Since the verify step is done after all deployments are completed, I believe the behavior should be that all deployments get rolled back even if they did not fail. See:
https://github.com/reactiveops/rok8s-scripts/blob/master/bin/k8s-deploy#L188

A possible issue is if the deploy command is called multiple times but with a different DEPLOYMENTS variable each time and then the verify is called multiple times. In that case not all deployments would get rolled back if one fails.

**Comment by ejether** [comment]
I agree that the verify step happens after the deploy so it _shouldn't_ ever undo a deployment that isn't the current. However, I think it never hurts to be more explict. Perhaps we can leaverage the `--to-revision=0: The revision to rollback to. Default to 0 (last revision)` flag, grab that value before the deployment begins and, if the verify fails, explicitly rollback to that revision.  Would that alay your concern @coreypobrien

**Comment by coreypobrien** [comment]
Looking back I think you're both right; I was off in a weird tangent that shouldn't ever happen. I'm good with this!

**Pull request merged**
