### PR TITLE
Insert extravars variable for `helm_deploy`

### PR DESCRIPTION
**Pull request by InAnimaTe**
Solving https://github.com/reactiveops/rok8s-scripts/issues/236

### CODE REVIEW

**Comment by InAnimaTe** [comment]
@sudermanjr heads up; not sure if you can also review.

**Comment by sudermanjr** [comment]
Seems fine to me.  Not sure what's up with testing, I will look.  In the meantime, will you please bump the minor version in setup.py to 7.23.0?

**Comment by InAnimaTe** [comment]
Done! in https://github.com/reactiveops/rok8s-scripts/pull/237/commits/cf5563e0fe15eef53edcab17b60b3a00f9e65cae

**Comment by sudermanjr** [comment]
I fixed it so that the tests will run next time.  We require shellcheck to pass on changes, so here's the output of shellcheck on the helm-deploy script:

```
In bin/helm-deploy line 61:
    ${ROK8S_HELM_DEPLOY_EXTRAARGS} \
    ^----------------------------^ SC2086: Double quote to prevent globbing and word splitting.
```

That should trigger a retest once you put quotes around that.  Thanks for sticking with this one!

**Comment by InAnimaTe** [comment]
no problem, thx for raising; fixed in https://github.com/reactiveops/rok8s-scripts/pull/237/commits/b1fdf5e828d13ec8702c8a5e04bb8795f68c9898
Let's see if tests pass!

**Comment by sudermanjr** [comment]
Failed, but not due to anything in your PR.  I will go ahead and merge this and fix the other stuff later.

**Comment by sudermanjr** [comment]
Released as version 7.23.0 in ci-images and for pip installs.  NPM install is broken for that version, which may or may not get fixed.

**Pull request merged**
