### PR TITLE
don't skip latest tag

### PR DESCRIPTION
**Pull request by matthewadams**
@endzyme, I think I got too smart for my britches on [my last PR](https://github.com/reactiveops/rok8s-scripts/pull/213), specifically at https://github.com/reactiveops/rok8s-scripts/pull/213/files#diff-b9b833d4afe6201b6556bdb110dd8151R61.

This PR fixes that.  We _should_ be pushing the `latest` tag.

### CODE REVIEW

**Comment by endzyme** [comment]
Thanks @matthewadams - so if I understand the case here. 

1. Be default we won't push latest (based on default tags defined)
2. You're overriding the default push tags to push latest OR you're adding an additional push tag of `latest`

Is that correct?

**Comment by endzyme** [comment]
@matthewadams it should be available shortly as the ci-images upload to quay

**Comment by matthewadams** [comment]
@endzyme 
> If the intent was always to be able to upload a static image tag to a remote registry, then we probably didn't need to introduce DOCKER_LATEST_TAG override, but it doesn't really hurt anything (except complexity).

Actually, we _still_ need the override.  We avoid using the `latest` tag on any images because it's ambiguous, and, like version _ranges_, don't produce repeatable builds.  If, instead, you rely only on _exact_ versions of things, including Docker images, you know exactly what you're getting.

When we override `latest`, we override it with the git commit hash, because that's the _only_ tag that's unique.  Using the git tag or branch for the Docker tag is ultimately ambiguous, because, well, the tag could always be deleted and recreated to point at some other commit in the repo, and the branch, ultimately, only a pointer to a commit (see https://git-scm.com/book/en/v1/Git-Branching-What-a-Branch-Is: "A branch in Git is simply a lightweight movable pointer to one of these commits").  Now, to be _completely_ clear, one should _always_ use the Docker image tag that is the git commit hash, but that's just not very human-friendly.  So, we add exact semantic version tags that are aliases to that Docker image, just for us dumb humans, who understand semantic version strings better than git commit hashes.

This was the impetus driving https://github.com/reactiveops/rok8s-scripts/pull/213.  It took me a while to notice that the Docker tag with the git commit hash was missing (after all, I'm a dumb human and it's difficult to search for or notice the absence of something), and when I did, it was too late to include the fix in `v7.20.0`, so I had to create this PR to ensure that our "latest" tag (the one with the git commit hash) is pushed, so that we at least have the One True Docker Image™️ in our image repository, along with all of its aliases:
image

Capice?

[If only Docker tags supported the `+` character](https://github.com/docker/distribution/issues/1201), we'd _really_ be in business.  In any case, thanks for accepting the PRs.  Now I can upgrade my `.gitlab-ci.yml` scripts to use `7.20.1` and continue on to the next problem, because, well, the problems never end...  :)

**Comment by ejether** [comment]
@matthewadams  are you using something external to Rok8s-scripts to build, push, and deploy the git commit tagged image? I only ask because that behavior is built into Rok8s-scripts for the exact reason you outlined above. If you are using another process layered on top of Rok8s-scripts, you can likely optimize you build scripts.

**Comment by endzyme** [comment]
@matthewadams Thanks for the context on the problem you're solving. As an aside, in our pipelines we generally set `$CI_SHA1` as the git commit hash instead of utilizing latest. In our environments we generally build on ephemeral build agents, and thus tag the original `${DOCKERTAG}:${DOCKER_LATEST_TAG}` as `${REMOTE}/${DOCKERTAG}:${<allTheDefaultTags>}` to make sure we get the specific build to the remote registry. 

If I understand correctly, you're overriding `${DOCKER_LATEST_TAG}` with a commit sha you inject at the job runtime and then add that sha string to the list of `${DOCKER_TAG_VERSIONS}`? If so that makes sense and it's just two ways of doing the same action. As EJ mentioned in the above comment, the default behavior for `rok8s-scripts` does this, but only if you know to set the `${CI_SHA1}=${<SomeGitCommitSha>}`.

Thanks again for the contribution and taking the time for all the commentary and adjustments!

**Comment by matthewadams** [comment]
@ejether & @endzyme No, we are only using rok8s-scripts to build & push our Docker images.  We are using our own `helm` commands to deploy the images into k8s.  I'll take a look at the scripts when I have time to see if I can optimize them according to what y'all said.  We're on gitlab, so it's as easy as setting `CI_SHA1="${GIT_COMMIT_SHA}"`.

**Pull request merged**
