### PR TITLE
Attempting to maintain backwards compatibility while allowing the int…

### LINKED ISSUE #47: v3.7.0 Breaks docker-pull when called without -f
and is not backwards compatible. I think this will start to cause issues with many of the existing circleci implementations.

### PR DESCRIPTION
**Pull request by ejether**
…ent of the script to use a default config file when a specific file is not passed in, and the default exists but not use the default file when a config file is passed in

fixes #47

### CODE REVIEW

**Comment by philipcristiano** [comment]
In testing this it appears that users not passing in `-f` will still get a `Config file, [PATH], not found.` In testing the `$CONFIG_FILE` was empty and was trying to read the config from a dir, not a file.

**Comment by ejether** [comment]
I believe I fixed that test now. Do you prefer this solution, provided it works, or do you perfer to revert as in https://github.com/reactiveops/k8s-scripts/pull/49 ?

I like this better because I can see value in separating configs.

**Comment by philipcristiano** [comment]
At the moment I'm in favor of reverting but can take a look again on Friday when I have more time. There is a large chunk committed that comments out a bunch of things that would need to be dropped from the commit before merging.

**Comment by philipcristiano** [comment]
We've made a backwards incompatible release since this was opened that requires a config file and makes this less needed. 

I will close this for now. @ejether if you would like to continue on this feel free to re-open.

**Pull request closed without merging**
