### PR TITLE
Update Helm Version in CI-Image

### PR DESCRIPTION
**Pull request by InAnimaTe**
New helm version which adds some awesome features like `--atomic` flag for safer deploys.

*edit* CI fail is something to do with credentials :(

### CODE REVIEW

**Comment by InAnimaTe** [comment]
@robscott @sudermanjr can I get some eyes on this? Thanks.

**Comment by sudermanjr** [comment]
Sorry for the slow response, and thanks for the contribution!

We have had some internal discussion about how to handle versioning and have opened #248 to address that and the upgrade to helm 2.13.0.

**Comment by robscott** [comment]
Hey @InAnimaTe, thanks for the PR! Unfortunately with our current versioning practices, and Helm's pattern of backwards incompatibility, Helm upgrades can be a bit complicated. Because rok8s-scripts currently tries to use semver for versioning, many that use the corresponding ci-images choose to use v7 as their baseline without pinning to a minor or patch version, and instead automatically pulling the latest v7 release of rok8s-scripts as part of their CI workflows.

Unfortunately even minor updates to Helm can be backwards incompatible. If we were to merge this PR as is and release a new minor rok8s-scripts release, we'd risk breaking CI workflows for anyone using rok8s-scripts 7.x with clusters running Tiller 2.12 or older. 

We've had a number of discussions about how we can best support this going forward, and we're working on a new larger major 8.0 release that will include clearer versioning guidelines. Our plan going forward will be to bump rok8s-scripts versions at the same level as dependency versions, so a new minor version of kubectl, helm, or others would result in a new minor version of rok8s-scripts, even if that was potentially backwards incompatible for some use cases.

Our longer term goal is to decouple dependency versions with rok8s-scripts versions, but of course that's more complex and will take some time to implement. 

We hope to get this v8 release out shortly with updated versions of both helm and kubectl. We'll let you know when that's ready to go.

**Comment by sudermanjr** [comment]
@InAnimaTe I just released v8.0.0 of rok8s-scripts.  This has the new helm that you were looking for.  Thanks for your patience!

**Pull request closed without merging**
